name = "RecZoo"
uuid = "a2d3a4f8-6081-5b5c-b23e-93f26afe21d9"
keywords = ["recommendation", "recommender"]
license = "MIT"
desc = "A collection of recommendation models and examples"
version = "0.0.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

